### PR TITLE
Improvements Phase

### PR DESCRIPTION
**Pull request by Nitzantomer1998**
Optimize Performances.

### CODE REVIEW

**Comment by Nitzantomer1998** [comment]
Solving Issue #21

**Comment by TwilightMercy** [comment]
I can confirm this is the correct method to search for tv shows through Wizdom's API
(Using same method in kodi subtitles addon)

Nitzan - Are you the dev of this? : )
https://stremio-addons.netlify.app/universal-hebrew-subtitles#

**Comment by Nitzantomer1998** [comment]
Since there was no response, I decided to build a solution myself. I focused on creating better-structured code and optimizing the addon performances. Additionally, I've integrated a few more websites into the addon, making it more universal and keep going.

Soon (when i finished my exams), i will work on a configuration option that allows users to select which websites they want to use for subtitles. Currently, it utilizes the Wizdom API & OpenSubtitles API (only for Hebrew).

**Comment by maormagori** [comment]
Hey @Nitzantomer1998 ,
First off a big thank you for picking up the glove and fixing things by yourself.
Both this addon and the Ktuvit one have admittedly become somewhat neglected as I shifted my focus away from Stremio and onto other projects. Your interest, along with that of others who have reached out privately, has reminded me how stale they were.
I'll find the time this weekend to review your contributions and refactor this outdated project.
Let me know if there are any other areas I should focus on!

Again, thanks for contributing 🙌

**Comment by maormagori** [comment]
Btw,
I'll also revamp [Ktuvit's addon](https://github.com/maormagori/ktuvit-stremio) while I'm at it so feel free to go over it and open issues/PR accordingly.

**Comment by Nitzantomer1998** [comment]
Solving Issue #23

**Comment by Nitzantomer1998** [comment]
Solved Issue #24.

I apologize if it's hard to track due to the numerous commits, as I was trying to be thorough. The project is now structured more appropriately, with services, controllers, configurations, and more, making it easier to grow and maintain.

Please note that I recommend implementing a .env file for sensitive information in the deployment (baseConfig.js).

Additionally, I couldn't understand how your logger worked, so I deleted it to test the application. If you continue using a logger, I suggest switching to Winston, as it's shorter and easier to use.

**Comment by maormagori** [comment]
Hey @Nitzantomer1998,

I'm currently reviewing your PR, and as you suspected, it's quite extensive. I realize I haven't provided any contribution guidelines, so it's understandable. There are certainly some valuable suggestions within your PR, although it's apparent that you had grander plans in mind when drafting it (referring to your awesome addon project 😄).

To ensure sustainability, I've decided to close this PR for now and focus on refactoring the current project while implementing automated tests for PRs. This approach will enable us to handle PRs more efficiently. If this interests you, I'd welcome your assistance! However, if you prefer, feel free to open new, focused PRs to address specific areas of the project that you believe require updating.

I want to emphasize that this decision isn't meant to diminish the effort you've invested. It's simply about facilitating a thorough discussion of each change and maintaining the manageable scope of this project.

P.S. If you still wish I'll go over the code provided and comment my 2 cents on it, LMK! 
Cheers🙏

**Comment by maormagori** [comment]
By the way,
The logger implemented was used to stream logs to a dedicated Splunk instance as the PaaS platform this addon runs doesn't persist logs : (.
That Splunk instance is long gone so I'll have to find different solution.

**Pull request closed without merging**
